/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vereinsmanager;

import java.awt.event.ItemEvent;
import java.util.ArrayList;

/**
 *
 * @author Timo
 */
public class SelectTrainingszeitenDialog extends javax.swing.JFrame {

    /**
     * Creates new form SelectTrainingszeitenDialog
     */
    private MannschaftDialog parent;
    private String mannschaftsBezeichnung;
    private ArrayList<Trainingszeit> trainingszeiten;

    public SelectTrainingszeitenDialog() {
    }

    public SelectTrainingszeitenDialog(MannschaftDialog parent, String mannschaftsBezeichnung) {
        initComponents();
        this.parent = parent;
        this.mannschaftsBezeichnung = mannschaftsBezeichnung;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMontag = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        tfvonMontag = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfBisMontag = new javax.swing.JTextField();
        cbDienstag = new javax.swing.JCheckBox();
        cbMittwoch = new javax.swing.JCheckBox();
        cbFreitag = new javax.swing.JCheckBox();
        cbDonnerstag = new javax.swing.JCheckBox();
        cbSamstag = new javax.swing.JCheckBox();
        cbSonntag = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        tfvonDienstag = new javax.swing.JTextField();
        tfBisDienstag = new javax.swing.JTextField();
        tfvonMittwoch = new javax.swing.JTextField();
        tfBisMittwoch = new javax.swing.JTextField();
        tfvonDonnerstag = new javax.swing.JTextField();
        tfBisDonnerstag = new javax.swing.JTextField();
        tfvonFreitag = new javax.swing.JTextField();
        tfBisFreitag = new javax.swing.JTextField();
        tfvonSamstag = new javax.swing.JTextField();
        tfBisSamstag = new javax.swing.JTextField();
        tfvonSonntag = new javax.swing.JTextField();
        tfBisSonntag = new javax.swing.JTextField();
        btnVerwerfen = new javax.swing.JButton();
        btnSpeichern = new javax.swing.JButton();
        lblWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbMontag.setText("Montag");
        cbMontag.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMontagItemStateChanged(evt);
            }
        });

        jLabel1.setText("Trainingszeiten auswählen");

        tfvonMontag.setEditable(false);
        tfvonMontag.setText("12:00");
        tfvonMontag.setEnabled(false);

        jLabel2.setText("Von (HH:MM)");

        tfBisMontag.setEditable(false);
        tfBisMontag.setText("16:00");
        tfBisMontag.setEnabled(false);
        tfBisMontag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBisMontagActionPerformed(evt);
            }
        });

        cbDienstag.setText("Dienstag");
        cbDienstag.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDienstagItemStateChanged(evt);
            }
        });

        cbMittwoch.setText("Mittwoch");
        cbMittwoch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMittwochItemStateChanged(evt);
            }
        });

        cbFreitag.setText("Freitag");
        cbFreitag.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFreitagItemStateChanged(evt);
            }
        });

        cbDonnerstag.setText("Donnerstag");
        cbDonnerstag.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDonnerstagItemStateChanged(evt);
            }
        });

        cbSamstag.setText("Samstag");
        cbSamstag.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSamstagItemStateChanged(evt);
            }
        });

        cbSonntag.setText("Sonntag");
        cbSonntag.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSonntagItemStateChanged(evt);
            }
        });

        jLabel4.setText("Bis (HH:MM)");

        tfvonDienstag.setEditable(false);
        tfvonDienstag.setText("12:00");
        tfvonDienstag.setEnabled(false);

        tfBisDienstag.setEditable(false);
        tfBisDienstag.setText("16:00");
        tfBisDienstag.setEnabled(false);
        tfBisDienstag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBisDienstagActionPerformed(evt);
            }
        });

        tfvonMittwoch.setEditable(false);
        tfvonMittwoch.setText("12:00");
        tfvonMittwoch.setEnabled(false);

        tfBisMittwoch.setEditable(false);
        tfBisMittwoch.setText("16:00");
        tfBisMittwoch.setEnabled(false);
        tfBisMittwoch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBisMittwochActionPerformed(evt);
            }
        });

        tfvonDonnerstag.setEditable(false);
        tfvonDonnerstag.setText("12:00");
        tfvonDonnerstag.setEnabled(false);

        tfBisDonnerstag.setEditable(false);
        tfBisDonnerstag.setText("16:00");
        tfBisDonnerstag.setEnabled(false);
        tfBisDonnerstag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBisDonnerstagActionPerformed(evt);
            }
        });

        tfvonFreitag.setEditable(false);
        tfvonFreitag.setText("12:00");
        tfvonFreitag.setEnabled(false);

        tfBisFreitag.setEditable(false);
        tfBisFreitag.setText("16:00");
        tfBisFreitag.setEnabled(false);
        tfBisFreitag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBisFreitagActionPerformed(evt);
            }
        });

        tfvonSamstag.setEditable(false);
        tfvonSamstag.setText("12:00");
        tfvonSamstag.setEnabled(false);

        tfBisSamstag.setEditable(false);
        tfBisSamstag.setText("16:00");
        tfBisSamstag.setEnabled(false);
        tfBisSamstag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBisSamstagActionPerformed(evt);
            }
        });

        tfvonSonntag.setEditable(false);
        tfvonSonntag.setText("12:00");
        tfvonSonntag.setEnabled(false);

        tfBisSonntag.setEditable(false);
        tfBisSonntag.setText("16:00");
        tfBisSonntag.setEnabled(false);
        tfBisSonntag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBisSonntagActionPerformed(evt);
            }
        });

        btnVerwerfen.setText("Verwerfen");
        btnVerwerfen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerwerfenActionPerformed(evt);
            }
        });

        btnSpeichern.setText("Speichern");
        btnSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeichernActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbSonntag, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbMontag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbMittwoch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbDienstag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbDonnerstag, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfvonMontag, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfBisMontag))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfvonDienstag, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfBisDienstag))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfvonMittwoch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfBisMittwoch))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfvonDonnerstag, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfBisDonnerstag))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tfvonSonntag, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfBisSonntag))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbSamstag, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbFreitag, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfvonFreitag, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfBisFreitag))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfvonSamstag, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfBisSamstag))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVerwerfen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSpeichern)))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMontag)
                    .addComponent(tfvonMontag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBisMontag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDienstag)
                    .addComponent(tfvonDienstag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBisDienstag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMittwoch)
                    .addComponent(tfvonMittwoch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBisMittwoch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDonnerstag)
                    .addComponent(tfvonDonnerstag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBisDonnerstag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFreitag)
                    .addComponent(tfvonFreitag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBisFreitag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSamstag)
                    .addComponent(tfvonSamstag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBisSamstag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSonntag)
                    .addComponent(tfvonSonntag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBisSonntag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpeichern)
                    .addComponent(btnVerwerfen))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBisMontagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBisMontagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBisMontagActionPerformed

    private void tfBisDienstagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBisDienstagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBisDienstagActionPerformed

    private void tfBisMittwochActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBisMittwochActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBisMittwochActionPerformed

    private void tfBisDonnerstagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBisDonnerstagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBisDonnerstagActionPerformed

    private void tfBisFreitagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBisFreitagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBisFreitagActionPerformed

    private void tfBisSamstagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBisSamstagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBisSamstagActionPerformed

    private void tfBisSonntagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBisSonntagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBisSonntagActionPerformed

    private void btnVerwerfenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerwerfenActionPerformed
        parent.EditTrainingszeitenDialog.dispose();
        parent.ChangetfBezeichnungCanEdit(true);
    }//GEN-LAST:event_btnVerwerfenActionPerformed

    private void btnSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeichernActionPerformed
        checkBoxenAuswerten();
    }//GEN-LAST:event_btnSpeichernActionPerformed

    private void cbMontagItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMontagItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            tfvonMontag.setEditable(false);
            tfvonMontag.setEnabled(false);
            tfBisMontag.setEditable(false);
            tfBisMontag.setEnabled(false);
        } else {
            tfvonMontag.setEditable(true);
            tfvonMontag.setEnabled(true);
            tfBisMontag.setEditable(true);
            tfBisMontag.setEnabled(true);
        }
    }//GEN-LAST:event_cbMontagItemStateChanged

    private void cbDienstagItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDienstagItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            tfvonDienstag.setEditable(false);
            tfvonDienstag.setEnabled(false);
            tfBisDienstag.setEditable(false);
            tfBisDienstag.setEnabled(false);
        } else {
            tfvonDienstag.setEditable(true);
            tfvonDienstag.setEnabled(true);
            tfBisDienstag.setEditable(true);
            tfBisDienstag.setEnabled(true);
        }
    }//GEN-LAST:event_cbDienstagItemStateChanged

    private void cbMittwochItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMittwochItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            tfvonMittwoch.setEditable(false);
            tfvonMittwoch.setEnabled(false);
            tfBisMittwoch.setEditable(false);
            tfBisMittwoch.setEnabled(false);
        } else {
            tfvonMittwoch.setEditable(true);
            tfvonMittwoch.setEnabled(true);
            tfBisMittwoch.setEditable(true);
            tfBisMittwoch.setEnabled(true);
        }
    }//GEN-LAST:event_cbMittwochItemStateChanged

    private void cbDonnerstagItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDonnerstagItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            tfvonDonnerstag.setEditable(false);
            tfvonDonnerstag.setEnabled(false);
            tfBisDonnerstag.setEditable(false);
            tfBisDonnerstag.setEnabled(false);
        } else {
            tfvonDonnerstag.setEditable(true);
            tfvonDonnerstag.setEnabled(true);
            tfBisDonnerstag.setEditable(true);
            tfBisDonnerstag.setEnabled(true);
        }
    }//GEN-LAST:event_cbDonnerstagItemStateChanged

    private void cbFreitagItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFreitagItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            tfvonFreitag.setEditable(false);
            tfvonFreitag.setEnabled(false);
            tfBisFreitag.setEditable(false);
            tfBisFreitag.setEnabled(false);
        } else {
            tfvonFreitag.setEditable(true);
            tfvonFreitag.setEnabled(true);
            tfBisFreitag.setEditable(true);
            tfBisFreitag.setEnabled(true);
        }
    }//GEN-LAST:event_cbFreitagItemStateChanged

    private void cbSamstagItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSamstagItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            tfvonSamstag.setEditable(false);
            tfvonSamstag.setEnabled(false);
            tfBisSamstag.setEditable(false);
            tfBisSamstag.setEnabled(false);
        } else {
            tfvonSamstag.setEditable(true);
            tfvonSamstag.setEnabled(true);
            tfBisSamstag.setEditable(true);
            tfBisSamstag.setEnabled(true);
        }
    }//GEN-LAST:event_cbSamstagItemStateChanged

    private void cbSonntagItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSonntagItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            tfvonSonntag.setEditable(false);
            tfvonSonntag.setEnabled(false);
            tfBisSonntag.setEditable(false);
            tfBisSonntag.setEnabled(false);
        } else {
            tfvonSonntag.setEditable(true);
            tfvonSonntag.setEnabled(true);
            tfBisSonntag.setEditable(true);
            tfBisSonntag.setEnabled(true);
        }
    }//GEN-LAST:event_cbSonntagItemStateChanged

    private void checkBoxenAuswerten() {
        Boolean ungueltigeZeiten = false;
        trainingszeiten = new ArrayList<>();
        if (cbMontag.isSelected()) {
            Trainingszeit MontagsTraining = new Trainingszeit();
            MontagsTraining.setWochentag("Montag");
            String anfangszeit = tfvonMontag.getText();
            if (Validator.isValidTime(anfangszeit)) {
                MontagsTraining.setAnfangszeit(anfangszeit);
            } else {
                ungueltigeZeiten = true;
            }
            String endzeit = tfBisMontag.getText();
            if (Validator.isValidTime(endzeit)) {
                MontagsTraining.setEndzeit(endzeit);
            } else {
                ungueltigeZeiten = true;
            }
            trainingszeiten.add(MontagsTraining);
        }

        if (cbDienstag.isSelected()) {
            Trainingszeit DienstagsTraining = new Trainingszeit();
            DienstagsTraining.setWochentag("Dienstag");
            String anfangszeit = tfvonDienstag.getText();
            if (Validator.isValidTime(anfangszeit)) {
                DienstagsTraining.setAnfangszeit(anfangszeit);
            } else {
                ungueltigeZeiten = true;
            }
            String endzeit = tfBisDienstag.getText();
            if (Validator.isValidTime(endzeit)) {
                DienstagsTraining.setEndzeit(endzeit);
            } else {
                ungueltigeZeiten = true;
            }
            trainingszeiten.add(DienstagsTraining);
        }

        if (cbMittwoch.isSelected()) {
            Trainingszeit MittwochsTraining = new Trainingszeit();
            MittwochsTraining.setWochentag("Mittwoch");
            String anfangszeit = tfvonMittwoch.getText();
            if (Validator.isValidTime(anfangszeit)) {
                MittwochsTraining.setAnfangszeit(anfangszeit);
            } else {
                ungueltigeZeiten = true;
            }
            String endzeit = tfBisMittwoch.getText();
            if (Validator.isValidTime(endzeit)) {
                MittwochsTraining.setEndzeit(endzeit);
            } else {
                ungueltigeZeiten = true;
            }
            trainingszeiten.add(MittwochsTraining);
        }

        if (cbDonnerstag.isSelected()) {
            Trainingszeit DonnerstagsTraining = new Trainingszeit();
            DonnerstagsTraining.setWochentag("Donnerstag");
            String anfangszeit = tfvonDonnerstag.getText();
            if (Validator.isValidTime(anfangszeit)) {
                DonnerstagsTraining.setAnfangszeit(anfangszeit);
            } else {
                ungueltigeZeiten = true;
            }
            String endzeit = tfBisDonnerstag.getText();
            if (Validator.isValidTime(endzeit)) {
                DonnerstagsTraining.setEndzeit(endzeit);
            } else {
                ungueltigeZeiten = true;
            }
            trainingszeiten.add(DonnerstagsTraining);
        }

        if (cbFreitag.isSelected()) {
            Trainingszeit FreitagsTraining = new Trainingszeit();
            FreitagsTraining.setWochentag("Freitag");
            String anfangszeit = tfvonFreitag.getText();
            if (Validator.isValidTime(anfangszeit)) {
                FreitagsTraining.setAnfangszeit(anfangszeit);
            } else {
                ungueltigeZeiten = true;
            }
            String endzeit = tfBisFreitag.getText();
            if (Validator.isValidTime(endzeit)) {
                FreitagsTraining.setEndzeit(endzeit);
            } else {
                ungueltigeZeiten = true;
            }
            trainingszeiten.add(FreitagsTraining);
        }

        if (cbSamstag.isSelected()) {
            Trainingszeit SamstagsTraining = new Trainingszeit();
            SamstagsTraining.setWochentag("Samstag");
            String anfangszeit = tfvonSamstag.getText();
            if (Validator.isValidTime(anfangszeit)) {
                SamstagsTraining.setAnfangszeit(anfangszeit);
            } else {
                ungueltigeZeiten = true;
            }
            String endzeit = tfBisSamstag.getText();
            if (Validator.isValidTime(endzeit)) {
                SamstagsTraining.setEndzeit(endzeit);
            } else {
                ungueltigeZeiten = true;
            }
            trainingszeiten.add(SamstagsTraining);
        }

        if (cbSonntag.isSelected()) {
            Trainingszeit SonntagsTraining = new Trainingszeit();
            SonntagsTraining.setWochentag("Sonntag");
            String anfangszeit = tfvonSonntag.getText();
            if (Validator.isValidTime(anfangszeit)) {
                SonntagsTraining.setAnfangszeit(anfangszeit);
            } else {
                ungueltigeZeiten = true;
            }
            String endzeit = tfBisSonntag.getText();
            if (Validator.isValidTime(endzeit)) {
                SonntagsTraining.setEndzeit(endzeit);
            } else {
                ungueltigeZeiten = true;
            }
            trainingszeiten.add(SonntagsTraining);
        }
        if (ungueltigeZeiten == true) {
            lblWarning.setText("<html><b>Mindestens eine Zeitangabe ist ungültig!</b></html>");
        } else {
            lblWarning.setText(null);
            parent.setTrainingszeiten(trainingszeiten);
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectTrainingszeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectTrainingszeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectTrainingszeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectTrainingszeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectTrainingszeitenDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpeichern;
    private javax.swing.JButton btnVerwerfen;
    private javax.swing.JCheckBox cbDienstag;
    private javax.swing.JCheckBox cbDonnerstag;
    private javax.swing.JCheckBox cbFreitag;
    private javax.swing.JCheckBox cbMittwoch;
    private javax.swing.JCheckBox cbMontag;
    private javax.swing.JCheckBox cbSamstag;
    private javax.swing.JCheckBox cbSonntag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JTextField tfBisDienstag;
    private javax.swing.JTextField tfBisDonnerstag;
    private javax.swing.JTextField tfBisFreitag;
    private javax.swing.JTextField tfBisMittwoch;
    private javax.swing.JTextField tfBisMontag;
    private javax.swing.JTextField tfBisSamstag;
    private javax.swing.JTextField tfBisSonntag;
    private javax.swing.JTextField tfvonDienstag;
    private javax.swing.JTextField tfvonDonnerstag;
    private javax.swing.JTextField tfvonFreitag;
    private javax.swing.JTextField tfvonMittwoch;
    private javax.swing.JTextField tfvonMontag;
    private javax.swing.JTextField tfvonSamstag;
    private javax.swing.JTextField tfvonSonntag;
    // End of variables declaration//GEN-END:variables
}
